-- @description Snap selected tcpfx envelope points to semitones
-- @author J Reverb
-- @version 1.0
-- @metapackage
-- @provides
--   [main] jreverb_Snap selected tcpfx envelope points to semitones/jreverb_Snap selected tcpfx envelope points to semitones positive 24 steps.lua
--   [main] jreverb_Snap selected tcpfx envelope points to semitones/jreverb_Snap selected tcpfx envelope points to semitones negative 24 steps.lua
--   [main] jreverb_Snap selected tcpfx envelope points to semitones/jreverb_Snap selected tcpfx AI envelope points to semitones positive 24 steps.lua
--   [main] jreverb_Snap selected tcpfx envelope points to semitones/jreverb_Snap selected tcpfx AI envelope points to semitones negative 24 steps.lua
-- @about
--   A convenient way to snap envelope point values to semitones for Pitch Wheel automation.
--   Plus/minus 12 semitones.
--
--   Currently 2 versions for Main tcpfx envelope lane and tcpfx Automation items (AI).
