-- @description Resample notes
-- @author daodan
-- @version 1.0.0-1
-- @changelog Packaging: fix incorrectly renamed Presets directory
-- @metapackage
-- @provides
--   [main] daodan_Resample notes/daodan_Resample notes.lua
--   [main=main,midi_editor] daodan_Resample notes/daodan_Resample notes - GUI.lua
--   daodan_Resample notes/Resample Notes Presets/daodan_Duplicate notes octave up (with fx).lua
--   daodan_Resample notes/Resample Notes Presets/daodan_Duplicate notes octave up.lua
--   daodan_Resample notes/Resample Notes Presets/daodan_Resample notes default.lua
--   daodan_Resample notes/Resample Notes Presets/daodan_Reverse notes and sample +pitch.lua
--   daodan_Resample notes/Resample Notes Presets/daodan_Reverse notes and sample.lua
--   daodan_Resample notes/Resample Notes Presets/daodan_Reversed on midi ch 2.lua
--   daodan_Resample notes/Resample Notes Presets/daodan_Reversed on new track.lua
--   daodan_Resample notes/Resample Notes Presets/daodan_Swell FX (reverse sample).lua
-- @link Forum thread https://forum.cockos.com/showthread.php?t=297511
-- @about
--   #Resample notes - render selected notes, load to sampler (rs5k)
--
--   Midi Editor script to automatically copy selected notes to new item,
--   apply fx, load sample to sampler, set root note in sampler,
--   remove new item, mute originally selected notes in original item
--   and insert root note in the corresponding position.
--   Basically. There are several options here so you can change the behavior
--   to suit your needs.
--   You can change them in [USER SETTINGS] section in code in main script
--   or preset scripts inside "Resample notes Presets" folder
--   or via GUI script (Resample notes - GUI.lua).

