-- @description JRT_Navigate-Zoom vertically OR move notes up or down ignoring key
-- @author JRTaylorMusic
-- @version 1.0
-- @metapackage
-- @provides
--   [main] JRT_Navigate-Zoom vertically OR move notes up or down ignoring key/JRT_Navigate-Zoom in vertically OR move notes up ignoring key.lua
--   [main] JRT_Navigate-Zoom vertically OR move notes up or down ignoring key/JRT_Navigate-Zoom out vertically OR move notes down ignoring key.lua
-- @about Midi Editor navigation; if note(s) selected, move up or down, ignoring key; if no notes selected, Zoom Vertically In or Out.
