-- @description Track-based item selection
-- @author Triode
-- @version 0.72
-- @metapackage
-- @provides
--   [main] triode_Track-based item selection/Track-based item selection.lua
--   [main] triode_Track-based item selection/Track-based item range selection.lua
--   [main] triode_Track-based item selection/Track-based split items (select left).lua
--   [main] triode_Track-based item selection/Track-based split items (select right).lua
--   [main] triode_Track-based item selection/Unselect all items (track-based item selection).lua
--   [main] triode_Track-based item selection/Track-based non-contiguous item selection.lua
--   [main] triode_Track-based item selection/Record Toggle (compatible with track based item selection).lua
--   triode_Track-based item selection/Play/Stop Toggle (compatible with track based item selection).lua
--   [main] triode_Track-based item selection/Individual item selection (compatible with track-based item selection).lua
--   [main] triode_Track-based item selection/Individual item range selection (compatible with track-based item selection).lua
--   [main] triode_Track-based item selection/Individual non-contiguous item selection (compatible with track-based item selection).lua
-- @link http://www.outoftheboxsounds.com/
-- @donation If you like this script please support https://www.paypal.com/paypalme/outoftheboxsounds
-- @about
--   Map this to media item left-click in mouse modifiers to allow selection of items based on the folder or track group they are contained in.  This script also includes individual item selection and selection of items across all tracks.
--
--   Requires SWS exclusive toggles B1 to B4 on the toolbar which correspond to the following item selection modes:
--
--   B1: Folder-based item selection
--   B2: Item selection across all tracks
--   B3: Individual item selection
--   B4: Track group based item selection
--
--   This script is for the first click to select.  Download the other track based scripts to get item range selection (shift-click), toggle selection, item split (select right or left) using the same modes.
--
--   There are also scripts for unselect all items and making newly recorded items create selections compatible with the above actions.
--
--   None of these scripts run anything in the background.
--   No undo point is created by the item selection scripts (unless you specifically set item select undo in reaper's preferences)

