-- @description Pitch scale generator
-- @author Will Develop
-- @version 1.0
-- @link
--   My Website https://will-records.tk
--   Forum thread https://forum.cockos.com/showthread.php?p=2239383
-- @about
--   # Pitch scale generator
--
--   This script allows you to generate a scale from the lowest note to the highest note.
--    
--   # INTRODUCTION:
--      
--   1. Select an audio item
--   2. Open the script
--   3. Set the Root Note on the pitch of the item
--   4. Set the lowest Note of your scale
--   5. Set the highest Note of your scale
--   6. Set which algorithm you are using. Pitch-algorithm or Playrate
--   7. Click "Create", so that the scale is generated
--      
--   # !IMPORTANT!:
--   1. You need to install the "Lokasenna's GUI library v2 for Lua" about ReaPack
--   2. And Run the Action "Script: Set Lokasenna_GUI v2 library path.lua"

--[[
  INFO:
    - ReaScript Name: Pitch Scale Generator
    - Author: Will Develop 
    - Website: https://www.will-records.tk
    - Repository URI: https://github.com/Will-Develop/Pitch_Scale_Generator.git
	- Forum: https://forum.cockos.com/showthread.php?p=2239383#post2239383
    - REAPER: 6.02
    - Version: 1.0
  
  DESCRIPTION:
    
    This script allows you to generate a scale
    from the lowest note to the highest note.
    
    INTRODUCTION:
      
      1.Select an audio item
      2.Open the script
      3.Set the Root Note on the pitch of the item
      4.Set the lowest Note of your scale
      5.Set the highest Note of your scale
      6.Set which algorithm you are using. Pitch-algorithm or Playrate
      7.Click "Create", so that the scale is generated
      
    !IMPORTANT!:
      1.You need to install the "Lokasenna's GUI library v2 for Lua" about ReaPack
      2.And Run the Action "Script: Set Lokasenna_GUI v2 library path.lua"
 
--]]
--GUI Script was generated by Lokasenna's GUI Builder


local lib_path = reaper.GetExtState("Lokasenna_GUI", "lib_path_v2")
if not lib_path or lib_path == "" then
    reaper.MB("Couldn't load the Lokasenna_GUI library. Please install 'Lokasenna's GUI library v2 for Lua', available on ReaPack, then run the 'Set Lokasenna_GUI v2 library path.lua' script in your Action List.", "Whoops!", 0)
    return
end
loadfile(lib_path .. "Core.lua")()




GUI.req("Classes/Class - Label.lua")()
GUI.req("Classes/Class - Menubox.lua")()
GUI.req("Classes/Class - Options.lua")()
GUI.req("Classes/Class - Button.lua")()
-- If any of the requested libraries weren't found, abort the script.
if missing_lib then return 0 end



GUI.name = "Pitch_Scale_Generator"
GUI.x, GUI.y, GUI.w, GUI.h = 0, 0, 256, 288
GUI.anchor, GUI.corner = "mouse", "C"


--This is the code from the "Expand selected items length to start and end of their source" Script by X-Raym_Expand
function set_new_item_length()

  reaper.Undo_BeginBlock();

  count_sel_items = reaper.CountSelectedMediaItems(0);

  for i_length = 0,count_sel_items,1 do 
    
    item = reaper.GetSelectedMediaItem(0,0);
    take = reaper.GetActiveTake(item);
    
    item_pos = reaper.GetMediaItemInfo_Value(item,"D_POSITION");
    item_len = reaper.GetMediaItemInfo_Value(item,"D_LENGTH");
    item_snap = reaper.GetMediaItemInfo_Value(item,"D_SNAPOFFSET");
    
    take_off = reaper.GetMediaItemTakeInfo_Value(take, "D_STARTOFFS");
    take_rate = reaper.GetMediaItemTakeInfo_Value(take,"D_PLAYRATE");
    
    take_off_comp = take_off * (1/take_rate);
    
    reaper.SetMediaItemInfo_Value(item, "D_POSITION", item_pos - take_off_comp);
    reaper.SetMediaItemInfo_Value(item, "D_LENGTH", item_len + take_off_comp);
    reaper.SetMediaItemInfo_Value(item, "D_SNAPOFFSET", item_snap + take_off_comp);
    
    reaper.SetMediaItemTakeInfo_Value(take, "D_STARTOFFS", 0);
    
    item_snap = reaper.GetMediaItemInfo_Value(item,"D_SNAPOFFSET");
       if item_snap < 0 then
         reaper.SetMediaItemInfo_Value(item, "D_SNAPOFFSET", 0);
       end
       
    reaper.Main_OnCommand(40612, 0);
    
  end
  
  reaper.Undo_EndBlock("Expand selected items length to start and end of their source", -1);

end

--Executed when the "Create" button is pressed
function create()
  --setting and checking, all necessary parts are selected
  sel_item = reaper.GetSelectedMediaItem(0,0)
    if not sel_item then
      reaper.ShowMessageBox("Please select a audio item", "Error", 0)
      return 0
    else
      sel_take = reaper.GetActiveTake(sel_item)
        if not sel_take then
          reaper.ShowMessageBox("Please select a audio item take", "Error", 0)
        end
    end
    
  sel_take = reaper.GetActiveTake(sel_item)
    if not sel_take then
      reaper.ShowMessageBox("Please select a audio item take", "Error", 0)
      return 0
    else
    
  track = reaper.GetMediaItem_Track(sel_item)
      if not track then 
        reaper.ShowMessageBox("Please select a the Track of the Item.", "Error", 0)
        return 0
      end
  -------------------------------------------------------------------------    
      
      
      --Set input fields to variables
      root_note = GUI.Val("menubox_root_note") -1
      low_note = GUI.Val("menubox_lowest_note") -1
      high_note = GUI.Val("menubox_highest_note") -1
      if GUI.Val("checkbox_use_playrate") == true then use_playrate = 1 else use_playrate = 0 end
      -------------------------------------------------------------------------------------------
      
      
      --Calculation: how often the item has to be copied and what is the lowest pitch
      copy_item = (high_note - low_note) -1
      pitch_lowest_note = root_note - low_note --Calculation: How low must the lowest note be
      new_item_name_count = low_note - 1 --Calculation of the Note Number for the Item Name
      
      --This prevents the lowest note from being larger than the highest note (flips the formula)
      if copy_item < 0 then 
        copy_item = (low_note - high_note) -1
        pitch_lowest_note = root_note - high_note --Calculation: how low must the highest note be (because: flips the formula)
        new_item_name_count = high_note - 1 --Calculation of the Note Number for the Item Name (with formula flip)
        
      end
      -------------------------------------------------------------------------------------
      
      
      _, sel_item_name = reaper.GetSetMediaItemTakeInfo_String( sel_take, "P_NAME", "", false) --save the original name of the selected item
      
      
      --Copy and transpose loop
      for i=-1,copy_item,1 do  
          
        --Set variables again
        sel_item = reaper.GetSelectedMediaItem(0,0)
        track = reaper.GetMediaItem_Track(sel_item)
        sel_take = reaper.GetActiveTake(sel_item)
        pos_item_start = reaper.GetMediaItemInfo_Value(sel_item,"D_POSITION")
        pos_item_length = reaper.GetMediaItemInfo_Value(sel_item,"D_LENGTH")
        -------------------------------------------------------------------
        
        
        --Separate: the original item from the copies
        if i <= -1 then
          pos = pos_item_start + pos_item_length*2
        else
          pos = pos_item_start + pos_item_length
        end
        ---------------------------------------------
        
        --Copy loop
        reaper.SetEditCurPos(pos, false, false)
        reaper.SetOnlyTrackSelected(track)
        reaper.Main_OnCommand(40914, 0) -- Select first track as last touched
        reaper.Main_OnCommand(40698, 0) -- Copy Items
        reaper.Main_OnCommand(40058, 0) -- Paste Items
        sel_item = reaper.GetSelectedMediaItem(0,0)
        sel_take = reaper.GetActiveTake(sel_item)
        ------------------------------------------------------------------------
        
        
        --Set the pitch modes
        if i >= -1 then
          if use_playrate == 1 then
            reaper.SetMediaItemTakeInfo_Value(sel_take,"B_PPITCH",0)
            reaper.SetMediaItemTakeInfo_Value(sel_take,"D_PLAYRATE",2^(((pitch_lowest_note * -1)+i+1)/12))
            set_new_item_length()
          else 
            reaper.SetMediaItemTakeInfo_Value(sel_take,"D_PITCH",pitch_lowest_note*(-1) + i+1)
          end
        end
        ------------------------------------------------------------------------------------
        
        
        --set the new item name
        if copy_item < 0 then
          new_item_name_count = new_item_name_count - 1
        else
          new_item_name_count = new_item_name_count + 1
        end
          
        if new_item_name_count == 0 then new_item_name_note = "C-1" end
        if new_item_name_count == 1 then new_item_name_note = "C#-1" end
        if new_item_name_count == 2 then new_item_name_note = "D-1" end
        if new_item_name_count == 3 then new_item_name_note = "D#-1" end
        if new_item_name_count == 4 then new_item_name_note = "E-1" end
        if new_item_name_count == 5 then new_item_name_note = "F-1" end
        if new_item_name_count == 6 then new_item_name_note = "F#-1" end
        if new_item_name_count == 7 then new_item_name_note = "G-1" end
        if new_item_name_count == 8 then new_item_name_note = "G#-1" end
        if new_item_name_count == 9 then new_item_name_note = "A-1" end
        if new_item_name_count == 10 then new_item_name_note = "A#-1" end
        if new_item_name_count == 11 then new_item_name_note = "B-1" end
        
        if new_item_name_count == 12 then new_item_name_note = "C0" end
        if new_item_name_count == 13 then new_item_name_note = "C#0" end
        if new_item_name_count == 14 then new_item_name_note = "D0" end
        if new_item_name_count == 15 then new_item_name_note = "D#0" end
        if new_item_name_count == 16 then new_item_name_note = "E0" end
        if new_item_name_count == 17 then new_item_name_note = "F0" end
        if new_item_name_count == 18 then new_item_name_note = "F#0" end
        if new_item_name_count == 19 then new_item_name_note = "G0" end
        if new_item_name_count == 20 then new_item_name_note = "G#0" end
        if new_item_name_count == 21 then new_item_name_note = "A0" end
        if new_item_name_count == 22 then new_item_name_note = "A#0" end
        if new_item_name_count == 23 then new_item_name_note = "B0" end
        
        if new_item_name_count == 24 then new_item_name_note = "C1" end
        if new_item_name_count == 25 then new_item_name_note = "C#1" end
        if new_item_name_count == 26 then new_item_name_note = "D1" end
        if new_item_name_count == 27 then new_item_name_note = "D#1" end
        if new_item_name_count == 28 then new_item_name_note = "E1" end
        if new_item_name_count == 29 then new_item_name_note = "F1" end
        if new_item_name_count == 30 then new_item_name_note = "F#1" end
        if new_item_name_count == 31 then new_item_name_note = "G1" end
        if new_item_name_count == 32 then new_item_name_note = "G#1" end
        if new_item_name_count == 33 then new_item_name_note = "A1" end
        if new_item_name_count == 34 then new_item_name_note = "A#1" end
        if new_item_name_count == 35 then new_item_name_note = "B1" end  
        
        if new_item_name_count == 36 then new_item_name_note = "C2" end
        if new_item_name_count == 37 then new_item_name_note = "C#2" end
        if new_item_name_count == 38 then new_item_name_note = "D2" end
        if new_item_name_count == 39 then new_item_name_note = "D#2" end
        if new_item_name_count == 40 then new_item_name_note = "E2" end
        if new_item_name_count == 41 then new_item_name_note = "F2" end
        if new_item_name_count == 42 then new_item_name_note = "F#2" end
        if new_item_name_count == 43 then new_item_name_note = "G2" end
        if new_item_name_count == 44 then new_item_name_note = "G#2" end
        if new_item_name_count == 45 then new_item_name_note = "A2" end
        if new_item_name_count == 46 then new_item_name_note = "A#2" end
        if new_item_name_count == 47 then new_item_name_note = "B2" end 
        
        if new_item_name_count == 48 then new_item_name_note = "C3" end
        if new_item_name_count == 49 then new_item_name_note = "C#3" end
        if new_item_name_count == 50 then new_item_name_note = "D3" end
        if new_item_name_count == 51 then new_item_name_note = "D#3" end
        if new_item_name_count == 52 then new_item_name_note = "E3" end
        if new_item_name_count == 53 then new_item_name_note = "F3" end
        if new_item_name_count == 54 then new_item_name_note = "F#3" end
        if new_item_name_count == 55 then new_item_name_note = "G3" end
        if new_item_name_count == 56 then new_item_name_note = "G#3" end
        if new_item_name_count == 57 then new_item_name_note = "A3" end
        if new_item_name_count == 58 then new_item_name_note = "A#3" end
        if new_item_name_count == 59 then new_item_name_note = "B3" end    
        
        if new_item_name_count == 60 then new_item_name_note = "C4" end
        if new_item_name_count == 61 then new_item_name_note = "C#4" end
        if new_item_name_count == 62 then new_item_name_note = "D4" end
        if new_item_name_count == 63 then new_item_name_note = "D#4" end
        if new_item_name_count == 64 then new_item_name_note = "E4" end
        if new_item_name_count == 65 then new_item_name_note = "F4" end
        if new_item_name_count == 66 then new_item_name_note = "F#4" end
        if new_item_name_count == 67 then new_item_name_note = "G4" end
        if new_item_name_count == 68 then new_item_name_note = "G#4" end
        if new_item_name_count == 69 then new_item_name_note = "A4" end
        if new_item_name_count == 70 then new_item_name_note = "A#4" end
        if new_item_name_count == 71 then new_item_name_note = "B4" end
        
        if new_item_name_count == 72 then new_item_name_note = "C5" end
        if new_item_name_count == 73 then new_item_name_note = "C#5" end
        if new_item_name_count == 74 then new_item_name_note = "D5" end
        if new_item_name_count == 75 then new_item_name_note = "D#5" end
        if new_item_name_count == 76 then new_item_name_note = "E5" end
        if new_item_name_count == 77 then new_item_name_note = "F5" end
        if new_item_name_count == 78 then new_item_name_note = "F#5" end
        if new_item_name_count == 79 then new_item_name_note = "G5" end
        if new_item_name_count == 80 then new_item_name_note = "G#5" end
        if new_item_name_count == 81 then new_item_name_note = "A5" end
        if new_item_name_count == 82 then new_item_name_note = "A#5" end
        if new_item_name_count == 83 then new_item_name_note = "B5" end
        
        if new_item_name_count == 84 then new_item_name_note = "C6" end
        if new_item_name_count == 85 then new_item_name_note = "C#6" end
        if new_item_name_count == 86 then new_item_name_note = "D6" end
        if new_item_name_count == 87 then new_item_name_note = "D#6" end
        if new_item_name_count == 88 then new_item_name_note = "E6" end
        if new_item_name_count == 89 then new_item_name_note = "F6" end
        if new_item_name_count == 90 then new_item_name_note = "F#6" end
        if new_item_name_count == 91 then new_item_name_note = "G6" end
        if new_item_name_count == 92 then new_item_name_note = "G#6" end
        if new_item_name_count == 93 then new_item_name_note = "A6" end
        if new_item_name_count == 94 then new_item_name_note = "A#6" end
        if new_item_name_count == 95 then new_item_name_note = "B6" end

        if new_item_name_count == 96 then new_item_name_note = "C7" end
        if new_item_name_count == 97 then new_item_name_note = "C#7" end
        if new_item_name_count == 98 then new_item_name_note = "D7" end
        if new_item_name_count == 99 then new_item_name_note = "D#7" end
        if new_item_name_count == 100 then new_item_name_note = "E7" end
        if new_item_name_count == 101 then new_item_name_note = "F7" end
        if new_item_name_count == 102 then new_item_name_note = "F#7" end
        if new_item_name_count == 103 then new_item_name_note = "G7" end
        if new_item_name_count == 104 then new_item_name_note = "G#7" end
        if new_item_name_count == 105 then new_item_name_note = "A7" end
        if new_item_name_count == 106 then new_item_name_note = "A#7" end
        if new_item_name_count == 107 then new_item_name_note = "B7" end
        
        if new_item_name_count == 108 then new_item_name_note = "C8" end
        if new_item_name_count == 109 then new_item_name_note = "C#8" end
        if new_item_name_count == 110 then new_item_name_note = "D8" end
        if new_item_name_count == 111 then new_item_name_note = "D#8" end
        if new_item_name_count == 112 then new_item_name_note = "E8" end
        if new_item_name_count == 113 then new_item_name_note = "F8" end
        if new_item_name_count == 114 then new_item_name_note = "F#8" end
        if new_item_name_count == 115 then new_item_name_note = "G8" end
        if new_item_name_count == 116 then new_item_name_note = "G#8" end
        if new_item_name_count == 117 then new_item_name_note = "A8" end
        if new_item_name_count == 118 then new_item_name_note = "A#8" end
        if new_item_name_count == 119 then new_item_name_note = "B8" end
        
        if new_item_name_count == 120 then new_item_name_note = "C9" end
        if new_item_name_count == 121 then new_item_name_note = "C#9" end
        if new_item_name_count == 122 then new_item_name_note = "D9" end
        if new_item_name_count == 123 then new_item_name_note = "D#9" end
        if new_item_name_count == 124 then new_item_name_note = "E9" end
        if new_item_name_count == 125 then new_item_name_note = "F9" end
        if new_item_name_count == 126 then new_item_name_note = "F#9" end
        if new_item_name_count == 127 then new_item_name_note = "G9" end
          
          
        reaper.GetSetMediaItemTakeInfo_String( sel_take, "P_NAME", new_item_name_count .. "_" .. new_item_name_note .. "_" .. sel_item_name, true) --change the Item Name
        -----------------------------------------------------------------------------------------------------------------  
        
          
      end --end of for loop
      
    end --end of "sel_take"
  
end --end of function "create()


GUI.New("menubox_highest_note", "Menubox", {
    z = 11,
    x = 96.0,
    y = 160.0,
    w = 128,
    h = 20,
    caption = "Highest Note",
    optarray = {"0: C-1", "1: C#-1", "2: D-1", "3: D#-1", "4: E-1", "5: F-1", "6: F#-1", "7: G-1", "8: G#-1", "9: A-1", "10: A#-1", "11: B-1", "12: C0", "13: C#0", "14: D0", "15: D#0", "16: E0", "17: F0", "18: F#0", "19: G0", "20: G#0", "21: A0", "22: A#0", "23: B0", "24: C1", "25: C#1", "26: D1", "27: D#1", "28: E1", "29: F1", "30: F#1", "31: G1", "32: G#1", "33: A1", "34: A#1", "35: B1", "36: C2", "37: C#2", "38: D2", "39: D#2", "40: E2", "41: F2", "42: F#2", "43: G2", "44: G#2", "45: A2", "46: A#2", "47: B2", "48: C3", "49: C#3", "50: D3", "51: D#3", "52: E3", "53: F3", "54: F#3", "55: G3", "56: G#3", "57: A3", "58: A#3", "59: B3", "60: C4", "61: C#4", "62: D4", "63: D#4", "64: E4", "65: F4", "66: F#4", "67: G4", "68: G#4", "69: A4", "70: A#4", "71: B4", "72: C5", "73: C#5", "74: D5", "75: D#5", "76: E5", "77: F5", "78: F#5", "79: G5", "80: G#5", "81: A5", "82: A#5", "83: B5", "84: C6", "85: C#6", "86: D6", "87: D#6", "88: E6", "89: F6", "90: F#6", "91: G6", "92: G#6", "93: A6", "94: A#6", "95: B6", "96: C7", "97: C#7", "98: D7", "99: D#7", "100: E7", "101: F7", "102: F#7", "103: G7", "104: G#7", "105: A7", "106: A#7", "107: B7", "108: C8", "109: C#8", "110: D8", "111: D#8", "112: E8", "113: F8", "114: F#8", "115: G8", "116: G#8", "117: A8", "118: A#8", "119: B8", "120: C9", "121: C#9", "122: D9", "123: D#9", "124: E9", "125: F9", "126: F#9", "127: G9"},
    retval = 1.0,
    font_a = 3,
    font_b = 4,
    col_txt = "txt",
    col_cap = "txt",
    bg = "wnd_bg",
    pad = 4,
    noarrow = false,
    align = 0
})

GUI.New("menubox_lowest_note", "Menubox", {
    z = 11,
    x = 96.0,
    y = 128.0,
    w = 128,
    h = 20,
    caption = "Lowest Note  ",
    optarray = {"0: C-1", "1: C#-1", "2: D-1", "3: D#-1", "4: E-1", "5: F-1", "6: F#-1", "7: G-1", "8: G#-1", "9: A-1", "10: A#-1", "11: B-1", "12: C0", "13: C#0", "14: D0", "15: D#0", "16: E0", "17: F0", "18: F#0", "19: G0", "20: G#0", "21: A0", "22: A#0", "23: B0", "24: C1", "25: C#1", "26: D1", "27: D#1", "28: E1", "29: F1", "30: F#1", "31: G1", "32: G#1", "33: A1", "34: A#1", "35: B1", "36: C2", "37: C#2", "38: D2", "39: D#2", "40: E2", "41: F2", "42: F#2", "43: G2", "44: G#2", "45: A2", "46: A#2", "47: B2", "48: C3", "49: C#3", "50: D3", "51: D#3", "52: E3", "53: F3", "54: F#3", "55: G3", "56: G#3", "57: A3", "58: A#3", "59: B3", "60: C4", "61: C#4", "62: D4", "63: D#4", "64: E4", "65: F4", "66: F#4", "67: G4", "68: G#4", "69: A4", "70: A#4", "71: B4", "72: C5", "73: C#5", "74: D5", "75: D#5", "76: E5", "77: F5", "78: F#5", "79: G5", "80: G#5", "81: A5", "82: A#5", "83: B5", "84: C6", "85: C#6", "86: D6", "87: D#6", "88: E6", "89: F6", "90: F#6", "91: G6", "92: G#6", "93: A6", "94: A#6", "95: B6", "96: C7", "97: C#7", "98: D7", "99: D#7", "100: E7", "101: F7", "102: F#7", "103: G7", "104: G#7", "105: A7", "106: A#7", "107: B7", "108: C8", "109: C#8", "110: D8", "111: D#8", "112: E8", "113: F8", "114: F#8", "115: G8", "116: G#8", "117: A8", "118: A#8", "119: B8", "120: C9", "121: C#9", "122: D9", "123: D#9", "124: E9", "125: F9", "126: F#9", "127: G9"},
    retval = 1.0,
    font_a = 3,
    font_b = 4,
    col_txt = "txt",
    col_cap = "txt",
    bg = "wnd_bg",
    pad = 4,
    noarrow = false,
    align = 0
})

GUI.New("checkbox_use_playrate", "Checklist", {
    z = 11,
    x = 70.0,
    y = 192.0,
    w = 110,
    h = 31,
    caption = "",
    optarray = {"Use Playrate"},
    dir = "v",
    pad = 4,
    font_a = 2,
    font_b = 3,
    col_txt = "txt",
    col_fill = "elm_fill",
    bg = "wnd_bg",
    frame = true,
    shadow = true,
    swap = nil,
    opt_size = 20
})

GUI.New("second_heading", "Label", {
    z = 11,
    x = 80.0,
    y = 64.0,
    caption = "by Will Develop",
    font = 3,
    color = "txt",
    bg = "wnd_bg",
    shadow = false
})

GUI.New("button_create", "Button", {
    z = 11,
    x = 100.0,
    y = 240.0,
    w = 48,
    h = 24,
    caption = "Create",
    font = 2,
    col_txt = "txt",
    col_fill = "elm_frame",
    func = create
})

GUI.New("heading", "Label", {
    z = 11,
    x = 16.0,
    y = 16.0,
    caption = "Pitch Scale Generator",
    font = 1,
    color = "txt",
    bg = "wnd_bg",
    shadow = false
})

GUI.New("menubox_root_note", "Menubox", {
    z = 11,
    x = 96.0,
    y = 96.0,
    w = 128,
    h = 20,
    caption = "Root Note      ",
    optarray = {"0: C-1", "1: C#-1", "2: D-1", "3: D#-1", "4: E-1", "5: F-1", "6: F#-1", "7: G-1", "8: G#-1", "9: A-1", "10: A#-1", "11: B-1", "12: C0", "13: C#0", "14: D0", "15: D#0", "16: E0", "17: F0", "18: F#0", "19: G0", "20: G#0", "21: A0", "22: A#0", "23: B0", "24: C1", "25: C#1", "26: D1", "27: D#1", "28: E1", "29: F1", "30: F#1", "31: G1", "32: G#1", "33: A1", "34: A#1", "35: B1", "36: C2", "37: C#2", "38: D2", "39: D#2", "40: E2", "41: F2", "42: F#2", "43: G2", "44: G#2", "45: A2", "46: A#2", "47: B2", "48: C3", "49: C#3", "50: D3", "51: D#3", "52: E3", "53: F3", "54: F#3", "55: G3", "56: G#3", "57: A3", "58: A#3", "59: B3", "60: C4", "61: C#4", "62: D4", "63: D#4", "64: E4", "65: F4", "66: F#4", "67: G4", "68: G#4", "69: A4", "70: A#4", "71: B4", "72: C5", "73: C#5", "74: D5", "75: D#5", "76: E5", "77: F5", "78: F#5", "79: G5", "80: G#5", "81: A5", "82: A#5", "83: B5", "84: C6", "85: C#6", "86: D6", "87: D#6", "88: E6", "89: F6", "90: F#6", "91: G6", "92: G#6", "93: A6", "94: A#6", "95: B6", "96: C7", "97: C#7", "98: D7", "99: D#7", "100: E7", "101: F7", "102: F#7", "103: G7", "104: G#7", "105: A7", "106: A#7", "107: B7", "108: C8", "109: C#8", "110: D8", "111: D#8", "112: E8", "113: F8", "114: F#8", "115: G8", "116: G#8", "117: A8", "118: A#8", "119: B8", "120: C9", "121: C#9", "122: D9", "123: D#9", "124: E9", "125: F9", "126: F#9", "127: G9"},
    retval = 1.0,
    font_a = 3,
    font_b = 4,
    col_txt = "txt",
    col_cap = "txt",
    bg = "wnd_bg",
    pad = 4,
    noarrow = false,
    align = 0
})







GUI.Init()
GUI.Main()

