-- @description Select source tracks of selected tracks receives recursively
-- @version 1.2
-- @author cfillion
-- @changelog
--   Fix a bug causing some tracks to not be selected in a single shot
--   Ignore muted receives
--   Select tracks down the folder hierarchy (obeying parent send)
-- @donation https://www.paypal.me/cfillion
-- @metapackage
-- @provides
--   [main] cfillion_Select destination tracks of selected tracks sends recursively.lua > cfillion_Select source tracks of selected tracks receives recursively.lua
--   [main] cfillion_Select destination tracks of selected tracks sends recursively.lua > cfillion_Select source tracks of selected tracks receives recursively (background).lua

-- The contents of this script is in `cfillion_Select destination tracks of selected tracks sends recursively.lua`.
