-- @description Select source tracks of selected tracks receives recursively
-- @version 1.2.1
-- @author cfillion
-- @changelog Fix crash when encountering feedback routings
-- @donation https://www.paypal.me/cfillion
-- @metapackage
-- @provides
--   [main] cfillion_Select destination tracks of selected tracks sends recursively.lua > cfillion_Select source tracks of selected tracks receives recursively.lua
--   [main] cfillion_Select destination tracks of selected tracks sends recursively.lua > cfillion_Select source tracks of selected tracks receives recursively (background).lua

-- The contents of this script is in `cfillion_Select destination tracks of selected tracks sends recursively.lua`.
