-- @description Select source tracks of selected tracks receives recursively
-- @version 1.0.2
-- @author cfillion
-- @changelog Simpler packaging using new ReaPack features (no other code changes).
-- @donation https://www.paypal.me/cfillion
-- @metapackage
-- @provides
--   [main] cfillion_Select destination tracks of selected tracks sends recursively.lua > cfillion_Select source tracks of selected tracks receives recursively.lua
--   [main] cfillion_Select destination tracks of selected tracks sends recursively.lua > cfillion_Select source tracks of selected tracks receives recursively (background).lua

-- The code of this script is in `cfillion_Select destination tracks of selected tracks sends recursively.lua`.
