-- @description Disable multichannel metering on selected tracks
-- @author Edgemeal
-- @version 1.0
-- @provides [main] Disable multichannel metering on selected tracks https://github.com/Edgemeal/ReaScripts/blob/master/Disable%20multichannel%20metering%20on%20selected%20tracks.lua
-- @link https://forum.cockos.com/showthread.php?t=208982
