-- @description Select next region in region manager window (Next/Previous)
-- @author Edgemeal
-- @version 1.00
-- @metapackage
-- @provides
--   [main] edgemeal_Select next region in region manager window (NextPrevious)/edgemeal_Select next region in region manager window.lua
--   [main] edgemeal_Select next region in region manager window (NextPrevious)/edgemeal_Select previous region in region manager window.lua
-- @link Forum https://forum.cockos.com/showthread.php?t=256856
-- @donation Donate https://www.paypal.me/Edgemeal
-- @about Requires js_ReaScriptAPI extension version v1.217 or later.

