--[[
Description: Lokasenna_Repeat Action
Version: 1.0.0
Author: Lokasenna
Donation: https://paypal.me/Lokasenna
Changelog:
	Initial release
Links:
	Forum Thread 
	Lokasenna's Website http://forum.cockos.com/member.php?u=10417
About: 
	Allows action IDs to repeated at a specified interval
	
	1. Use the included script 'Lokasenna_Repeat Action - Add new action.lua' to generate a script
	for each action you want to repeat.
	
	2. In Reaper's action list, use the 'Load' button and browse to:
		'Reaper/Scripts/ReaTeam Scripts/Various/Lokasenna_Repeat Action commands/"

	3. Select the scripts you generated.
	
	4. Each script will be individually accessible in the action list for you to bind to a shortcut key.
Extensions:
Provides:
	[nomain] Lokasenna_Repeat Action/Lokasenna_Repeat Action.lua
	[main] . > Lokasenna_Repeat Action/Lokasenna_Repeat Action - Add new action.lua
--]]

-- Licensed under the GNU GPL v3


local function Msg(str)
	reaper.ShowConsoleMsg(tostring(str).."\n")
end



local ret, csv = reaper.GetUserInputs("Repeat Action - Add new action", 4, "Action ID:,File alias:,How often (s),MIDI (y/n):", ",,0.6,n")


if ret then
	
	local act, alias, interval, midi = string.match(csv, "([^,]+),([^,]*),([^,]+),([^,]+)")
	
	--Msg(tostring(act).." "..tostring(alias).." "..tostring(midi))	
	
	if not (act and interval and midi) then
		reaper.ShowMessageBox("Invalid parameters.", "Whoops", 0)
		return 0
	end
	
	local script_path = debug.getinfo(1,'S').source:match[[^@?(.*[\/])[^\/]-$]]
						.. "Lokasenna Repeat Action - " 
						.. (alias or tostring(act))
						.. ".lua"
						
	local file = io.open(script_path, "w+") or nil
	
	if not file then
		reaper.ShowMessageBox("Couldn't create the file.", "Whoops", 0)
		return 0
	end
	
	local str_pre =
[=[--[[
	This file was generated by Lokasenna_Repeat Action - Add new action.lua
--]]


]=]

	local str_vars = 	  "act = "..act.."\n"
						.."interval = "..interval.."\n"
						.."midi = "..tostring(midi == "y").."\n\n"
	
	local str_suff =
[=[script_path = debug.getinfo(1,'S').source:match[[^@?(.*[\/])[^\/]-$]]
dofile(script_path .. "Lokasenna_Repeat Action.lua")]=]
	
	local str = str_pre .. str_vars .. str_suff
	
	file:write(str)
	
	io.close(file)
	
end
