-- @noindex
-- @author Ben 'Talagan' Babut
-- @license MIT
-- @description This file is part of MaCCLane

return {
    SECTION_MIDI_EDITOR                         = 32060,
    SECTION_MAIN                                = 100,

    ACTION_ME_TOGGLE_KEY_SNAP                   = 42471,
    ACTION_MAIN_USE_SAME_GRID_IN_ME_AND_ARRANGE = 42010,

    ACTION_ME_SET_GRID_TYPE_TO_STRAIGHT         = 41003,
    ACTION_ME_SET_GRID_TYPE_TO_TRIPLET          = 41004,
    ACTION_ME_SET_GRID_TYPE_TO_DOTTED           = 41005,
    ACTION_ME_SET_GRID_SIZE_TO_SWING            = 41006,

    ACTION_ME_SET_COLORING_VELOCITY     = 40738,
    ACTION_ME_SET_COLORING_CHANNEL      = 40739,
    ACTION_ME_SET_COLORING_PITCH        = 40740,
    ACTION_ME_SET_COLORING_SOURCE       = 40741,
    ACTION_ME_SET_COLORING_TRACK        = 40768,
    ACTION_ME_SET_COLORING_MEDIA_ITEM   = 40769,
    ACTION_ME_SET_COLORING_VOICE        = 41114,

    ACTION_SHOW_ALL_MIDI_CHANS = 40217,
    ACTION_TOGGLE_MIDI_CHAN    = 40643,

    ACTION_ME_SET_DOCKED = 40018
}
