-- @description FX presets navigation (7 scripts)
-- @author BuyOne
-- @website https://forum.cockos.com/member.php?u=134058
-- @version 1.1
-- @about
--   **6 scripts to navigate FX presets / automate FX presets change + 1 auxiliary script.**
--   **All complete with instructions.**
--   BuyOne_Cycle through focused FX presets forward (guide inside).lua
--
--   BuyOne_Cycle through focused FX presets backwards (guide inside).lua
--
--   BuyOne_Dedicated FX presets forward switcher (FX ID dependent) (guide inside).lua
--
--   BuyOne_Dedicated FX presets backwards switcher (FX ID dependent) (guide inside).lua
--
--   BuyOne_Dedicated FX presets forward switcher (TAG dependent) (guide inside).lua
--
--   BuyOne_Dedicated FX presets backwards switcher (TAG dependent) (guide inside).lua
--
--   BuyOne_Extract focused FX preset count, list, active preset number and name.lua
-- @metapackage
-- @provides
--   [main] BuyOne_FX presets navigation/BuyOne_Cycle through focused FX presets forward (guide inside).lua
--   [main] BuyOne_FX presets navigation/BuyOne_Cycle through focused FX presets backwards (guide inside).lua
--   [main] BuyOne_FX presets navigation/BuyOne_Dedicated FX presets forward switcher (FX ID dependent) (guide inside).lua
--   [main] BuyOne_FX presets navigation/BuyOne_Dedicated FX presets backwards switcher (FX ID dependent) (guide inside).lua
--   [main] BuyOne_FX presets navigation/BuyOne_Dedicated FX presets forward switcher (TAG dependent) (guide inside).lua
--   [main] BuyOne_FX presets navigation/BuyOne_Dedicated FX presets backwards switcher (TAG dependent) (guide inside).lua
--   [main] BuyOne_FX presets navigation/BuyOne_Extract focused FX preset count, active preset number and name.lua
