-- @description Save and restore selected tracks floating FX windows (4 slots)
-- @author Edgemeal
-- @version 1.02
-- @changelog Add support for Master track
-- @metapackage
-- @provides
--   [main] edgemeal_Save and restore selected tracks floating FX windows (4 slots)/edgemeal_Save selected tracks floating FX windows.lua > edgemeal_Save and restore selected tracks floating FX windows (4 slots)/edgemeal_Save selected tracks floating FX windows to slot 1.lua
--   [main] edgemeal_Save and restore selected tracks floating FX windows (4 slots)/edgemeal_Save selected tracks floating FX windows.lua > edgemeal_Save and restore selected tracks floating FX windows (4 slots)/edgemeal_Save selected tracks floating FX windows to slot 2.lua
--   [main] edgemeal_Save and restore selected tracks floating FX windows (4 slots)/edgemeal_Save selected tracks floating FX windows.lua > edgemeal_Save and restore selected tracks floating FX windows (4 slots)/edgemeal_Save selected tracks floating FX windows to slot 3.lua
--   [main] edgemeal_Save and restore selected tracks floating FX windows (4 slots)/edgemeal_Save selected tracks floating FX windows.lua > edgemeal_Save and restore selected tracks floating FX windows (4 slots)/edgemeal_Save selected tracks floating FX windows to slot 4.lua
--   [main] edgemeal_Save and restore selected tracks floating FX windows (4 slots)/edgemeal_Restore tracks floating FX windows.lua > edgemeal_Save and restore selected tracks floating FX windows (4 slots)/edgemeal_Restore tracks floating FX windows from slot 1.lua
--   [main] edgemeal_Save and restore selected tracks floating FX windows (4 slots)/edgemeal_Restore tracks floating FX windows.lua > edgemeal_Save and restore selected tracks floating FX windows (4 slots)/edgemeal_Restore tracks floating FX windows from slot 2.lua
--   [main] edgemeal_Save and restore selected tracks floating FX windows (4 slots)/edgemeal_Restore tracks floating FX windows.lua > edgemeal_Save and restore selected tracks floating FX windows (4 slots)/edgemeal_Restore tracks floating FX windows from slot 3.lua
--   [main] edgemeal_Save and restore selected tracks floating FX windows (4 slots)/edgemeal_Restore tracks floating FX windows.lua > edgemeal_Save and restore selected tracks floating FX windows (4 slots)/edgemeal_Restore tracks floating FX windows from slot 4.lua
-- @link Forum thread https://forum.cockos.com/showpost.php?p=2349852&postcount=2196
-- @donation https://www.paypal.me/Edgemeal

