-- @description Get and propagate last touched FX parameter to all instances
-- @author JRTaylorMusic
-- @version 1.0

-- Script generated by Lokasenna's GUI Builder


local lib_path = reaper.GetExtState("Lokasenna_GUI", "lib_path_v2")
if not lib_path or lib_path == "" then
    reaper.MB("Couldn't load the Lokasenna_GUI library. Please install 'Lokasenna's GUI library v2 for Lua', available on ReaPack, then run the 'Set Lokasenna_GUI v2 library path.lua' script in your Action List.", "Whoops!", 0)
    return
end
loadfile(lib_path .. "Core.lua")()


GUI.req("Classes/Class - Button.lua")()
GUI.req("Classes/Class - Textbox.lua")()
-- If any of the requested libraries weren't found, abort the script.
if missing_lib then return 0 end

------------------------------------
-------- Functions  ----------------
------------------------------------


function getFXinfo()
  retval, tracknumber, fxnumber, paramnumber = reaper.GetLastTouchedFX()
  if retval then
   tr =  reaper.CSurf_TrackFromID( tracknumber, false )
   retval, fxname = reaper.TrackFX_GetFXName( tr, fxnumber, '' )
   retval, parname = reaper.TrackFX_GetParamName( tr, fxnumber, paramnumber, '' )
   val = reaper.TrackFX_GetParamNormalized( tr, fxnumber, paramnumber)
   retval, valf = reaper.TrackFX_GetFormattedParamValue(  tr, fxnumber, paramnumber,'' )
   retval, trname = reaper.GetTrackName( tr, '' )

   GUI.Val("Textbox1", fxname)
   GUI.Val("Textbox2", parname)
   GUI.Val("Textbox3", valf)
   end
end


reaper.Undo_BeginBlock()
function propagate()

for ti=0,reaper.CountTracks()-1 do
  local track = reaper.GetTrack(0, ti)
  if track then
    for fi=0,reaper.TrackFX_GetCount(track)-1 do
      local _, fx_name = reaper.TrackFX_GetFXName(track, fi, '')
        if fxname == fx_name then
        reaper.TrackFX_SetParam(track, fi, paramnumber, val)
        end
      end
    end
  end
end

reaper.Undo_EndBlock("Get and propagate last touched FX parameter to all instances", -1)

------------------------------------
-------- Window settings -----------
------------------------------------

GUI.name = "Get and Propagate FX Parameter"
GUI.x, GUI.y, GUI.w, GUI.h = 0, 0, 300, 185
GUI.anchor, GUI.corner = "mouse", "C"

------------------------------------
-------- GUI Elements --------------
------------------------------------

GUI.New("Button2", "Button", {
    z = 11,
    x = 60,
    y = 130,
    w = 175,
    h = 24,
    caption = "Propagate to All Instances",
    font = 3,
    col_txt = "txt",
    col_fill = "elm_frame",
    func = propagate
})

GUI.New("Textbox1", "Textbox", {
    z = 11,
    x = 75,
    y = 20,
    w = 200,
    h = 20,
    caption = "FX Name",
    cap_pos = "left",
    font_a = 3,
    font_b = "monospace",
    color = "txt",
    bg = "wnd_bg",
    shadow = true,
    pad = 4,
    undo_limit = 20
})

GUI.New("Button1", "Button", {
    z = 11,
    x = 85,
    y = 90,
    w = 125,
    h = 24,
    caption = "Get Last Touched",
    font = 3,
    col_txt = "txt",
    col_fill = "elm_frame",
    func = getFXinfo
})

GUI.New("Textbox2", "Textbox", {
    z = 11,
    x = 75,
    y = 50,
    w = 100,
    h = 20,
    caption = "Parameter",
    cap_pos = "left",
    font_a = 3,
    font_b = "monospace",
    color = "txt",
    bg = "wnd_bg",
    shadow = true,
    pad = 4,
    undo_limit = 20
})

GUI.New("Textbox3", "Textbox", {
    z = 11,
    x = 225,
    y = 50,
    w = 50,
    h = 20,
    caption = "Value",
    cap_pos = "left",
    font_a = 3,
    font_b = "monospace",
    color = "txt",
    bg = "wnd_bg",
    shadow = true,
    pad = 4,
    undo_limit = 20
})


GUI.Init()
GUI.Main()
