-- @description Razor Edit - Fast Mode
-- @author sockmonkey72
-- @version 1.0
-- @changelog 1.0 initial upload
-- @metapackage
-- @provides
--   [main] sockmonkey72_Razor Edit - Fast Mode/sockmonkey72_Razor Edit - Fast Mode ON.eel
--   [main] sockmonkey72_Razor Edit - Fast Mode/sockmonkey72_Razor Edit - Fast Mode OFF.eel
-- @about
--   Inspired by [Kenny Gioia's "Razor Edit - Fast Mode in REAPER"](https://youtu.be/HEVKLiWkRkk), these two scripts make the appropriate changes to the Mouse Modifier preferences to support fast Razor Editing. Improved over what Kenny can do using standard actions is that the shift-modified left-drag actions are incorporated with the "ignoring snap" action variants.
--
--   Otherwise, you can follow Kenny's workflow in the video: create a new Cycle Action using these two scripts and toggle Razor Edit - Fast Mode on and off.

