-- @description Import/export track group names
-- @author nickstomp
-- @version 1.0.0
-- @metapackage
-- @provides
--   [main] nickstomp_Import Export track group names/nickstomp_Export track group names.lua
--   [main] nickstomp_Import Export track group names/nickstomp_Import track group names.lua
-- @about
--   # Export and import the track group names to a text file
--
--   This allows to export the group names from a project and import it into another one.
