name: check
on: [push, pull_request]
jobs:
  reapack-index:
    runs-on: ubuntu-latest
    steps:
    - name: Fetch repository
      uses: actions/checkout@v2
    - name: Install Pandoc
      run:  sudo apt-get install -yy pandoc
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
    - name: Install reapack-index
      run:  gem install reapack-index --pre
    - name: Validate packages
      run:  reapack-index --check
